/**
 * Interfaces and classes to implement a UnitOfWork. A UnitOfWork keeps track of changes on the Aggregates loaded from the underlying repository and allows to save them all in a single call.
 */

import {IAggregateRoot} from "../Aggregate/IAggregateRoot";
import {IKeyValueObject} from "../Entity/IKeyValueObject";
import {IEventHandler} from "../DomainEvents/IEventHandler";

// namespace DDDTools.UnitOfWork {


/**
 * Simple UnitOfWork for a single Repository.
 */
export interface IUnitOfWork<T extends IAggregateRoot<T, TKey>, TKey extends IKeyValueObject<TKey>> {

    /**
     * Retrieves an item from the Repository or from the UnitOfWork, given its Id.
     */
    getById(key: TKey): T;

    /**
     * Marks an item as deleted from the UnitOfWork (and from the Repository when the UoW will be saved)
     */
    deleteById(key: TKey): void;

    /**
     * Saves all the modified items in the UnitOfWork.
     */
    saveAll(): void;

    /**
     * Allows to register an handler for events generated by the UnitOfWork
     */
    registerHandler(eventTypeName: string, eventHandler: IEventHandler): void;

    /**
     * Allows to unregister an handler for events generated by the UnitOfWork
     */
    unregisterHandler(eventTypeName: string, eventHandler: IEventHandler): void;

}
// }